services:
  # --- BACKBONE: MESSAGING & STATE ---
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: rmq_broker
    hostname: rabbitmq
    ports:
      - "5672:5672"   # AMQP Protocol
      - "15672:15672" # Management UI
    networks:
      - data_plane

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    container_name: redis_state
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - data_plane
      - control_plane

  mongodb:
    image: mongo:latest
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - data_plane

  auth-service:
    build: 
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017/auth_db?authSource=admin
      - JWT_SECRET=eVOo6GoZns6NVDsZ7lCZ95XOa17PKzAj0+wsmZqHi3I=
    depends_on:
      mongodb:
        condition: service_healthy
    restart: on-failure
    networks: [data_plane]

  notification-service:
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    ports:
      - "3002:3002"
      - "9091:9091"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    networks: [data_plane]

  consumer-service:
    build:
      context: .
      dockerfile: ./services/consumer/Dockerfile
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017/jobs_db?authSource=admin
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: on-failure
    networks: [data_plane]

  webserver:
    build:
      context: .
      dockerfile: ./services/webserver/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017/jobs_db?authSource=admin
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    restart: on-failure
    networks: [data_plane]


  # --- HAProxy ---
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
      - "444:444"
      - "8404:8404"
      - "8405:8405"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./shared/certs/localhost.pem:/usr/local/etc/haproxy/certs/localhost.pem:ro
    depends_on:
      auth-service:
        condition: service_started
      webserver:
        condition: service_started
      notification-service:
        condition: service_started
    networks: [data_plane]

# --- OBSERVABILITY ---
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks: [data_plane]

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks: [data_plane]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin


networks:
  data_plane:    # for the traffic of Producer, Rabbit and Worker
  control_plane: # for Monitoring, Redis and the Regulator