scrape_configs:
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8405']
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'notification-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['notification-service:9091']
  - job_name: 'generic-consumer-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['consumer-service:9092']
  - job_name: 'soft-consumer-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['consumer-service:9093']
  - job_name: 'medium-consumer-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['consumer-service:9094']
  - job_name: 'hard-consumer-service'
    scrape_interval: 10s
    static_configs:
      - targets: ['consumer-service:9095']